enum ClipboardContentType {
  unknown,
  text,
  image,
  file,
  folder,
  link,
  audio,
  video,
  email,
  phone,
  color,
  ip,
  uuid,
  json;

  static ClipboardContentType fromValue(int value) => switch (value) {
    0 => text,
    1 => image,
    2 => file,
    3 => folder,
    4 => link,
    5 => audio,
    6 => video,
    7 => email,
    8 => phone,
    9 => color,
    10 => ip,
    11 => uuid,
    12 => json,
    _ => unknown,
  };

  int get value => switch (this) {
    unknown => -1,
    text => 0,
    image => 1,
    file => 2,
    folder => 3,
    link => 4,
    audio => 5,
    video => 6,
    email => 7,
    phone => 8,
    color => 9,
    ip => 10,
    uuid => 11,
    json => 12,
  };
}
