version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      actions-majors:
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
    groups:
      rust:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      rust-majors:
        patterns:
          - "*"
        update-types:
          - major
