coverage:
    precision: 2
    round: down
    ignore:
        - "core/lib/repository/sqlite_repository.g.dart"
        - "app/lib/l10n/app_localizations_en.dart"
        - "app/lib/l10n/app_localizations_es.dart"
        - "app/lib/shell"
        - "app/lib/services"
        - "app/lib/screens/settings_screen.dart"
        - "app/lib/main.dart"
        - "app/lib/helpers/url_helper.dart"

comment:
    layout: "reach,diff,flags,files"
    behavior: default
    require_changes: true

