[graph]
targets = [
  "x86_64-pc-windows-msvc",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
]

[advisories]
yanked = "deny"

[licenses]
allow = [
  "GPL-3.0-only",
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-3.0",
  "BSL-1.0",
  "Zlib",
]
confidence-threshold = 0.9
unused-allowed-license = "allow"

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
