import { Card } from "types.slint";
import { Theme } from "theme.slint";

export component LinkBody inherits VerticalLayout {
    in property <Card> card;
    height: Theme.body-link;
    spacing: 3px;

    Text {
        text: card.link-domain;
        color: Theme.accent;
        font-size: Theme.fs-meta;
        font-weight: 600;
        overflow: elide;
        wrap: no-wrap;
    }

    Text {
        text: card.link-path != "" ? card.link-path : card.squeezed;
        color: Theme.body;
        font-size: Theme.fs-body;
        overflow: elide;
        wrap: no-wrap;
    }
}
