export global Words {
    in property <string> hint;
    in property <string> footer;
    in property <string> paste-as;
    in property <string> open-it;
    in property <string> name-it;
    in property <int> name-room;
    in property <string> copy-it;
    in property <string> pin;
    in property <string> unpin;
    in property <string> remove;
    in property <string> one-kind;
    in property <string> many-kinds;
}
