#![cfg(target_os = "macos")]

pub mod activation;
pub mod clock;
pub mod dragging;
pub mod files;
pub mod floating;
pub mod frontmost;
pub mod keyboard;
pub mod keystroke;
pub mod media;
pub mod menu;
pub mod ocr;
pub mod pasteboard;
pub mod paths;
pub mod permissions;
pub mod pointer;
pub mod processes;
pub mod runloop;
pub mod theme;
pub mod titlebar;
pub mod translation;
