include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    sort_constructors_first: true
    use_super_parameters: true
    unnecessary_late: true
    require_trailing_commas: true

    # Safety
    avoid_print: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true

    # Documentation
    public_member_api_docs: false
