[package]
name = "cp-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
cp-core.workspace = true
rusqlite.workspace = true
xxhash-rust.workspace = true
blake3.workspace = true
thiserror.workspace = true

[dev-dependencies]
image.workspace = true
tempfile.workspace = true

[lints]
workspace = true
