name: core
description: "CopyPaste v2 — Core library: models, repository, services, config."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.11.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.0
  uuid: ^4.0.0
  archive: ^4.0.9
  image: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.0.0
  build_runner: ^2.0.0
  test: ^1.29.0
