name: "🐛 Bug Report"
description: "Report a technical issue or unexpected behavior"
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for helping us improve CopyPaste! 🙏
        Your report makes the app better for everyone.
        Before reporting, please make sure you're using the latest version.
  - type: input
    id: version
    attributes:
      label: "CopyPaste Version"
      description: "Check the version in Settings or the installer name."
      placeholder: "e.g., v1.0.0-beta.1"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      options:
        - "Windows 11 (23H2 or newer)"
        - "Windows 11 (Older version)"
        - "Windows 10 (1809+)"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "What happened?"
      description: "A clear and concise description of the bug."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "How can we make this happen again?"
      placeholder: "1. Copy a high-resolution image\n2. Open CopyPaste with Win+Alt+V\n3. Click on the item..."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Application Logs (optional)"
      description: |
        If you have logs, paste them here. You can find them at:
        `%LocalAppData%\CopyPaste\logs`
      placeholder: "Paste logs from the .txt files here..."
  - type: checkboxes
    id: checks
    attributes:
      label: "Technical Context"
      options:
        - label: "The issue persists after restarting the app"
          required: false
        - label: "I've checked the data folder at %LocalAppData%\\CopyPaste"
          required: false
  - type: textarea
    id: extra
    attributes:
      label: "Screenshots or Extra Info (optional)"
      description: "Screenshots help us understand the problem better."
      placeholder: "Drag and drop images here..."
