#![cfg(target_os = "windows")]

pub mod backdrop;
pub mod clipboard;
pub mod clock;
pub mod com;
pub mod dragging;
pub mod files;
pub mod formats;
pub mod frontmost;
pub mod keystroke;
pub mod media;
pub mod ocr;
pub mod ole;
pub mod paths;
pub mod permissions;
pub mod pointer;
pub mod reading;
pub mod source;
pub mod theme;
pub mod thumbnail;
pub mod window;
pub mod writing;
