import 'dart:async';
import 'dart:io';

import 'package:path/path.dart' as p;

import '../config/storage_config.dart';
import '../models/clipboard_item.dart';
import '../repository/i_clipboard_repository.dart';
import 'app_logger.dart';

class CleanupService {
  CleanupService(
    this._repository,
    this._getRetentionDays, {
    StorageConfig? storage,
    int Function()? getKeepBrokenDays,
    int Function()? getImagesQuotaMB,
  }) : _storage = storage,
       _getKeepBrokenDays = getKeepBrokenDays ?? (() => 30),
       _getImagesQuotaMB = getImagesQuotaMB ?? (() => 0);

  static const Duration _checkInterval = Duration(hours: 18);
  static const String _lastCleanupFileName = 'last_cleanup.txt';

  final IClipboardRepository _repository;
  int Function() _getRetentionDays;
  int Function() _getKeepBrokenDays;
  int Function() _getImagesQuotaMB;
  final StorageConfig? _storage;
  Timer? _timer;
  bool _disposed = false;

  String? _baseDirPath;

  String get _cleanupFilePath =>
      p.join(_baseDirPath ?? '', _lastCleanupFileName);

  void start(String baseDirPath) {
    _baseDirPath = baseDirPath;
    _timer = Timer.periodic(_checkInterval, (_) => runCleanupIfNeeded());
    runCleanupIfNeeded();
  }

  Future<void> runCleanupIfNeeded() async {
    if (_disposed) return;

    final lastCleanup = _loadLastCleanupDate();
    final now = DateTime.now().toUtc();
    if (lastCleanup.year == now.year &&
        lastCleanup.month == now.month &&
        lastCleanup.day == now.day) {
      return;
    }

    try {
      final retentionDays = _getRetentionDays();
      if (retentionDays > 0) {
        await _repository.clearOldItems(retentionDays, excludePinned: true);
      }
      _saveLastCleanupDate(now);
      await _cleanOrphanImages();
      await _enforceImagesQuota();
    } catch (e) {
      AppLogger.error('Cleanup failed: $e');
    }
  }

  DateTime _loadLastCleanupDate() {
    try {
      final file = File(_cleanupFilePath);
      if (file.existsSync()) {
        final content = file.readAsStringSync().trim();
        final parsed = DateTime.tryParse(content);
        if (parsed != null) return parsed.toUtc();
      }
    } catch (_) {}
    return DateTime.utc(2000);
  }

  void _saveLastCleanupDate(DateTime date) {
    try {
      final file = File(_cleanupFilePath);
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(date.toIso8601String());
    } catch (_) {}
  }

  void updateRetentionCallback(int Function() getter) {
    _getRetentionDays = getter;
  }

  void updateKeepBrokenCallback(int Function() getter) {
    _getKeepBrokenDays = getter;
  }

  void updateImagesQuotaCallback(int Function() getter) {
    _getImagesQuotaMB = getter;
  }

  void dispose() {
    _disposed = true;
    _timer?.cancel();
  }

  Future<void> _cleanOrphanImages() async {
    final storage = _storage;
    if (storage == null) return;
    try {
      await _trackBrokenExternalRefs();

      final allImageItems = await _repository.getImagePaths();
      final allThumbPaths = await _repository.getThumbPaths();
      final canonicalImagesDir = p.canonicalize(storage.imagesPath);
      final baseWithSep = canonicalImagesDir.endsWith(p.separator)
          ? canonicalImagesDir
          : '$canonicalImagesDir${p.separator}';

      // Items whose content is inside images/ (own captures): pass to orphan
      // cleanup so files without a matching item get deleted.
      // Items with external paths are never deleted — only logged if broken.
      final ownedPaths = <String>[];
      for (final path in allImageItems) {
        if (p.canonicalize(path).startsWith(baseWithSep)) {
          ownedPaths.add(path);
        }
      }

      // Own thumbnails generated by ThumbnailService live inside images/ as
      // `<id>_thumb.png`. They must be preserved by the orphan sweep.
      for (final tp in allThumbPaths) {
        if (p.canonicalize(tp).startsWith(baseWithSep)) {
          ownedPaths.add(tp);
        }
      }

      storage.cleanOrphanImages(ownedPaths);
    } catch (e) {
      AppLogger.error('Orphan image cleanup failed: $e');
    }
  }

  /// Walks all items with external file references; updates `brokenSince`
  /// when the source disappears and the volume is present, clears it when
  /// the source comes back, and purges items whose `brokenSince` exceeds
  /// `keepBrokenItemsDays`. The external file is never touched.
  Future<void> _trackBrokenExternalRefs() async {
    final storage = _storage;
    if (storage == null) return;
    final keepDays = _getKeepBrokenDays();
    final now = DateTime.now().toUtc();
    final cutoff = now.subtract(Duration(days: keepDays));
    final canonicalImagesDir = p.canonicalize(storage.imagesPath);
    final baseWithSep = canonicalImagesDir.endsWith(p.separator)
        ? canonicalImagesDir
        : '$canonicalImagesDir${p.separator}';

    final all = await _repository.getAll();
    for (final item in all) {
      final path = _externalPathForCheck(item, baseWithSep);
      if (path == null) continue;

      if (!isVolumePresent(path)) {
        // Volume offline: assume the file still exists. Keep brokenSince as
        // is so a temporary disconnection does not advance the purge clock.
        continue;
      }

      final exists = File(path).existsSync() || Directory(path).existsSync();
      if (exists) {
        if (item.brokenSince != null) {
          await _repository.update(item.copyWith(brokenSince: null));
        }
        continue;
      }

      // File missing with volume present.
      if (item.brokenSince == null) {
        AppLogger.warn('[CleanupService] broken external reference: "$path"');
        await _repository.update(item.copyWith(brokenSince: now));
        continue;
      }
      if (keepDays > 0 && item.brokenSince!.isBefore(cutoff)) {
        await _purgeBrokenItem(item);
      }
    }
  }

  /// Returns the external path to validate, or null when the item has no
  /// external file reference (own captures live inside `images/`).
  String? _externalPathForCheck(ClipboardItem item, String baseWithSep) {
    if (item.isPinned) return null;
    if (item.content.isEmpty) return null;
    final paths = item.content.split('\n').where((s) => s.isNotEmpty).toList();
    if (paths.length != 1) return null;
    final candidate = paths.first;
    if (!item.isFileBasedType) {
      // Image type: only treat as external when the path is outside images/.
      // Plain text/code/etc. never carry filesystem references.
      if (!_looksLikeFilesystemPath(candidate)) return null;
    }
    try {
      if (p.canonicalize(candidate).startsWith(baseWithSep)) return null;
    } catch (_) {
      return null;
    }
    return candidate;
  }

  bool _looksLikeFilesystemPath(String value) {
    if (value.length < 2) return false;
    if (value.contains('\n')) return false;
    if (Platform.isWindows) {
      return RegExp(r'^[a-zA-Z]:[\\/]').hasMatch(value) ||
          value.startsWith(r'\\');
    }
    return value.startsWith('/');
  }

  Future<void> _purgeBrokenItem(ClipboardItem item) async {
    AppLogger.warn(
      '[CleanupService] purging item with broken external reference '
      'beyond keepBrokenItemsDays: id=${item.id}',
    );
    final storage = _storage;
    if (storage != null) {
      final thumb = item.thumbPath;
      if (thumb != null) {
        try {
          final f = File(thumb);
          if (f.existsSync()) f.deleteSync();
        } catch (e) {
          AppLogger.warn('[CleanupService] could not delete thumb: $e');
        }
      }
    }
    await _repository.delete(item.id);
  }

  /// Enforces the user-configured `imagesQuotaMB` cap. When the total bytes
  /// stored under `images/` exceed the limit, deletes items from oldest to
  /// newest (by `createdAt`) until the directory drops back below the cap.
  /// Pinned items are never purged. Owned files are removed via the same
  /// canonical path validation used elsewhere — external paths referenced by
  /// items are never touched.
  Future<void> _enforceImagesQuota() async {
    final storage = _storage;
    if (storage == null) return;
    final quotaMB = _getImagesQuotaMB();
    if (quotaMB <= 0) return;
    final quotaBytes = quotaMB * 1024 * 1024;

    final canonicalImagesDir = p.canonicalize(storage.imagesPath);
    final baseWithSep = canonicalImagesDir.endsWith(p.separator)
        ? canonicalImagesDir
        : '$canonicalImagesDir${p.separator}';

    int currentBytes = _measureDirectoryBytes(canonicalImagesDir);
    if (currentBytes <= quotaBytes) return;

    AppLogger.warn(
      '[CleanupService] images/ ${(currentBytes / 1024 / 1024).toStringAsFixed(1)}MB '
      'exceeds quota ${quotaMB}MB; starting LRU purge',
    );

    final all = await _repository.getAll();
    final eligible = all.where((it) => !it.isPinned).toList()
      ..sort((a, b) => a.createdAt.compareTo(b.createdAt));

    var purged = 0;
    for (final item in eligible) {
      if (currentBytes <= quotaBytes) break;
      final freed = await _purgeOwnedFiles(item, baseWithSep);
      if (freed <= 0) continue;
      try {
        await _repository.delete(item.id);
      } catch (e) {
        AppLogger.warn('[CleanupService] quota: delete row failed: $e');
        continue;
      }
      currentBytes -= freed;
      purged++;
    }

    if (purged > 0) {
      AppLogger.warn(
        '[CleanupService] quota purge done: removed $purged items, '
        'now ${(currentBytes / 1024 / 1024).toStringAsFixed(1)}MB',
      );
    }
  }

  /// Sums the byte size of regular files directly inside [dir]. Recursion
  /// is intentionally omitted — `images/` is flat by design.
  int _measureDirectoryBytes(String dir) {
    try {
      final d = Directory(dir);
      if (!d.existsSync()) return 0;
      var total = 0;
      for (final entity in d.listSync(followLinks: false)) {
        if (entity is File) {
          try {
            total += entity.lengthSync();
          } catch (_) {}
        }
      }
      return total;
    } catch (_) {
      return 0;
    }
  }

  /// Deletes the per-item files this app owns (`<id>.png`, `<id>.bmp`,
  /// `<id>_thumb.png`, plus any path declared by the item that resolves
  /// inside `images/`). Returns the freed bytes. The external file pointed
  /// to by an item is never touched.
  Future<int> _purgeOwnedFiles(ClipboardItem item, String baseWithSep) async {
    final storage = _storage;
    if (storage == null) return 0;
    final candidates = <String>{
      p.join(storage.imagesPath, '${item.id}.png'),
      p.join(storage.imagesPath, '${item.id}.bmp'),
      p.join(storage.imagesPath, '${item.id}_thumb.png'),
    };
    final declared = item.thumbPath;
    if (declared != null && declared.isNotEmpty) candidates.add(declared);
    if (item.content.isNotEmpty) {
      for (final entry in item.content.split('\n')) {
        if (entry.isNotEmpty) candidates.add(entry);
      }
    }

    var freed = 0;
    for (final path in candidates) {
      try {
        final canonical = p.canonicalize(path);
        if (!canonical.startsWith(baseWithSep)) continue;
        final f = File(canonical);
        if (!f.existsSync()) continue;
        final bytes = f.lengthSync();
        f.deleteSync();
        freed += bytes;
      } catch (e) {
        AppLogger.warn('[CleanupService] quota: delete file failed: $e');
      }
    }
    return freed;
  }

  /// Best-effort check that the volume/mount carrying [path] is currently
  /// present. When the volume is offline (drive not mounted, NAS down,
  /// removable disk unplugged), callers should skip purge logic so the user
  /// does not lose history entries on a temporary disconnection.
  static bool isVolumePresent(String path) {
    try {
      if (Platform.isWindows) {
        if (path.startsWith(r'\\')) {
          // UNC: \\server\share\... — require server+share to be reachable.
          final parts = path.substring(2).split(RegExp(r'[\\/]'));
          if (parts.length < 2 || parts[0].isEmpty || parts[1].isEmpty) {
            return false;
          }
          final share = '\\\\${parts[0]}\\${parts[1]}';
          return Directory(share).existsSync();
        }
        final m = RegExp(r'^([a-zA-Z]):').firstMatch(path);
        if (m == null) return true;
        return Directory('${m.group(1)}:\\').existsSync();
      }
      if (Platform.isMacOS) {
        if (path.startsWith('/Volumes/')) {
          final rest = path.substring('/Volumes/'.length);
          final slash = rest.indexOf('/');
          final mount = slash < 0 ? rest : rest.substring(0, slash);
          if (mount.isEmpty) return false;
          return Directory('/Volumes/$mount').existsSync();
        }
        return true;
      }
      // Linux / others: best-effort; mount discovery is out of scope. Treat
      // as present so purge proceeds when the file is genuinely missing.
      return true;
    } catch (_) {
      return true;
    }
  }
}
