import 'dart:async';
import 'dart:io';

import 'package:path/path.dart' as p;

import '../config/storage_config.dart';
import '../repository/i_clipboard_repository.dart';
import 'app_logger.dart';

class CleanupService {
  CleanupService(
    this._repository,
    this._getRetentionDays, {
    StorageConfig? storage,
  }) : _storage = storage;

  static const Duration _checkInterval = Duration(hours: 18);
  static const String _lastCleanupFileName = 'last_cleanup.txt';

  final IClipboardRepository _repository;
  int Function() _getRetentionDays;
  final StorageConfig? _storage;
  Timer? _timer;
  bool _disposed = false;

  String? _baseDirPath;

  String get _cleanupFilePath =>
      p.join(_baseDirPath ?? '', _lastCleanupFileName);

  void start(String baseDirPath) {
    _baseDirPath = baseDirPath;
    _timer = Timer.periodic(_checkInterval, (_) => runCleanupIfNeeded());
    runCleanupIfNeeded();
  }

  Future<void> runCleanupIfNeeded() async {
    if (_disposed) return;

    final lastCleanup = _loadLastCleanupDate();
    final now = DateTime.now().toUtc();
    if (lastCleanup.year == now.year &&
        lastCleanup.month == now.month &&
        lastCleanup.day == now.day) {
      return;
    }

    try {
      final retentionDays = _getRetentionDays();
      if (retentionDays > 0) {
        await _repository.clearOldItems(retentionDays, excludePinned: true);
      }
      _saveLastCleanupDate(now);
      await _cleanOrphanImages();
    } catch (e) {
      AppLogger.error('Cleanup failed: $e');
    }
  }

  DateTime _loadLastCleanupDate() {
    try {
      final file = File(_cleanupFilePath);
      if (file.existsSync()) {
        final content = file.readAsStringSync().trim();
        final parsed = DateTime.tryParse(content);
        if (parsed != null) return parsed.toUtc();
      }
    } catch (_) {}
    return DateTime.utc(2000);
  }

  void _saveLastCleanupDate(DateTime date) {
    try {
      final file = File(_cleanupFilePath);
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(date.toIso8601String());
    } catch (_) {}
  }

  void updateRetentionCallback(int Function() getter) {
    _getRetentionDays = getter;
  }

  void dispose() {
    _disposed = true;
    _timer?.cancel();
  }

  Future<void> _cleanOrphanImages() async {
    final storage = _storage;
    if (storage == null) return;
    try {
      final allImageItems = await _repository.getImagePaths();
      final allThumbPaths = await _repository.getThumbPaths();
      final canonicalImagesDir = p.canonicalize(storage.imagesPath);
      final baseWithSep = canonicalImagesDir.endsWith(p.separator)
          ? canonicalImagesDir
          : '$canonicalImagesDir${p.separator}';

      // Items whose content is inside images/ (own captures): pass to orphan
      // cleanup so files without a matching item get deleted.
      // Items with external paths are never deleted — only logged if broken.
      final ownedPaths = <String>[];
      for (final path in allImageItems) {
        if (p.canonicalize(path).startsWith(baseWithSep)) {
          ownedPaths.add(path);
        } else if (!File(path).existsSync()) {
          // External reference whose file no longer exists. Log for
          // observability. UI warning overlay comes in Phase 3.
          AppLogger.warn('[CleanupService] broken external reference: "$path"');
        }
      }

      // Own thumbnails generated by ThumbnailService live inside images/ as
      // `<id>_thumb.png`. They must be preserved by the orphan sweep.
      for (final tp in allThumbPaths) {
        if (p.canonicalize(tp).startsWith(baseWithSep)) {
          ownedPaths.add(tp);
        }
      }

      storage.cleanOrphanImages(ownedPaths);
    } catch (e) {
      AppLogger.error('Orphan image cleanup failed: $e');
    }
  }
}
