use cp_core::formats::Catalog;

pub const CATALOG: Catalog = Catalog {
    hangs: &[],
    wasteful: &[
        "Embed Source",
        "Native",
        "OwnerLink",
        "ObjectLink",
        "Link Source",
        "Link Source Descriptor",
        "Link",
        "Object Descriptor",
        "Ole Private Data",
        "DataObject",
        "DataObjectAttributes",
        "DataObjectAttributesRequiringElevation",
        "Shell Object Offsets",
        "AsyncFlag",
        "ZoneIdentifier",
        "CF_ENHMETAFILE",
        "CF_METAFILEPICT",
        "CF_SYLK",
        "CF_DIF",
        "Biff12",
        "Biff8",
        "Biff5",
        "XML Spreadsheet",
        "CF_BITMAP",
        "FileGroupDescriptorW",
        "FileContents",
        "Shell IDList Array",
        "Chromium internal source RFH token",
        "FileName",
        "FileNameW",
    ],
    wanted: &[
        "CF_UNICODETEXT",
        "Rich Text Format",
        "HTML Format",
        "PNG",
        "CF_DIBV5",
        "CF_DIB",
        "CF_HDROP",
        "Csv",
        "Preferred DropEffect",
        "Chromium internal source URL",
        "CanIncludeInClipboardHistory",
    ],
    aliases: &[],
    concealed: &[
        "Clipboard Viewer Ignore",
        "ExcludeClipboardContentFromMonitorProcessing",
        "ExcludeClipboardDataFromMonitorProcessing",
    ],
    denied_when_zero: &["CanIncludeInClipboardHistory"],
    opaque_prefixes: &[],
    text: &["CF_UNICODETEXT", "Rich Text Format", "HTML Format", "Csv"],
    files: &["CF_HDROP"],
    images_by_preference: &["PNG", "CF_DIBV5", "CF_DIB"],
    equivalents: &[
        &["CF_UNICODETEXT", "CF_TEXT", "CF_OEMTEXT"],
        &["HTML Format", "text/html"],
    ],
    embeddable: &[
        "Embed Source",
        "Native",
        "Object Descriptor",
        "Link Source Descriptor",
        "Biff12",
        "Biff8",
        "Biff5",
        "XML Spreadsheet",
        "Csv",
    ],
    page_archives: &[],
};

#[cfg(test)]
#[path = "formats_test.rs"]
mod tests;
