use cp_core::formats::Catalog;

pub const CATALOG: Catalog = Catalog {
    hangs: &["com.apple.pasteboard.promised-suggested-file-name"],
    wasteful: &[
        "com.apple.icns",
        "com.microsoft.Link-Source",
        "com.microsoft.ObjectLink",
    ],
    wanted: &[
        "public.utf8-plain-text",
        "public.rtf",
        "com.apple.flat-rtfd",
        "public.html",
        "com.apple.webarchive",
        "public.png",
        "public.tiff",
        "public.file-url",
        "public.url",
        "public.url-name",
        "org.chromium.source-url",
    ],
    aliases: &[
        ("NSStringPboardType", "public.utf8-plain-text"),
        ("NeXT TIFF v4.0 pasteboard type", "public.tiff"),
        ("Apple PNG pasteboard type", "public.png"),
        ("NeXT Rich Text Format v1.0 pasteboard type", "public.rtf"),
        ("NeXT RTFD pasteboard type", "com.apple.flat-rtfd"),
        ("Apple HTML pasteboard type", "public.html"),
        ("Apple Web Archive pasteboard type", "com.apple.webarchive"),
    ],
    concealed: &[
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "PasswordPboardType",
    ],
    denied_when_zero: &[],
    opaque_prefixes: &["dyn.", "CorePasteboardFlavorType"],
    text: &[
        "public.utf8-plain-text",
        "public.rtf",
        "com.apple.flat-rtfd",
        "public.html",
        "com.apple.webarchive",
    ],
    files: &["public.file-url"],
    images_by_preference: &["public.png", "public.tiff"],
    equivalents: &[],
    embeddable: &[
        "com.apple.iWork.TSPNativeData",
        "com.apple.iWork.TSPNativeMetadata",
        "com.apple.iWork.TSPDescription",
        "com.microsoft.Embed-Source",
        "com.microsoft.Object-Descriptor",
        "com.microsoft.Link-Source-Descriptor",
        "com.microsoft.ObjectLink",
    ],
};

#[cfg(test)]
mod tests {
    use super::CATALOG;
    use cp_core::formats::{Family, Take};

    const SAFARI: &[&str] = &[
        "com.apple.webarchive",
        "Apple Web Archive pasteboard type",
        "com.apple.flat-rtfd",
        "NeXT RTFD pasteboard type",
        "public.rtf",
        "NeXT Rich Text Format v1.0 pasteboard type",
        "public.html",
        "Apple HTML pasteboard type",
        "public.utf8-plain-text",
        "NSStringPboardType",
        "com.apple.WebKit.custom-pasteboard-data",
    ];

    const FINDER: &[&str] = &[
        "public.file-url",
        "CorePasteboardFlavorType 0x6675726C",
        "dyn.ah62d4rv4gu8y6y4grf0gn5xbrzw1gydcr7u1e3cytf2gn",
        "NSFilenamesPboardType",
        "com.apple.finder.noderef",
        "fndf",
        "public.utf8-plain-text",
        "com.apple.icns",
        "public.tiff",
        "NeXT TIFF v4.0 pasteboard type",
    ];

    const PREVIEW: &[&str] = &[
        "public.png",
        "Apple PNG pasteboard type",
        "dyn.ah62d4rv4gu8zazwuqm10c6xemf1gq54uqm10c6xenv61a3k",
        "PVPboardInfoPboardType",
        "public.tiff",
        "NeXT TIFF v4.0 pasteboard type",
    ];

    const NUMBERS: &[&str] = &[
        "com.apple.iWork.TSPNativeData",
        "com.apple.iWork.TSPNativeMetadata",
        "com.apple.iWork.TSPDescription",
        "com.apple.iWork.pasteboardState.numberOfTables-1",
        "com.apple.iWork.pasteboardState.applicationName-Numbers",
        "com.apple.iWork.pasteboardState.hasTables",
        "com.apple.flat-rtfd",
        "NeXT RTFD pasteboard type",
        "com.apple.webarchive",
        "Apple Web Archive pasteboard type",
        "public.rtf",
        "NeXT Rich Text Format v1.0 pasteboard type",
        "public.utf16-external-plain-text",
        "CorePasteboardFlavorType 0x75743136",
        "public.utf8-plain-text",
        "NSStringPboardType",
        "public.html",
        "Apple HTML pasteboard type",
        "public.png",
        "Apple PNG pasteboard type",
        "com.adobe.pdf",
        "Apple PDF pasteboard type",
        "public.tiff",
        "NeXT TIFF v4.0 pasteboard type",
    ];

    const EXCEL: &[&str] = &[
        "public.html",
        "Apple HTML pasteboard type",
        "public.utf16-plain-text",
        "CorePasteboardFlavorType 0x75747874",
        "public.utf8-plain-text",
        "NSStringPboardType",
        "com.adobe.pdf",
        "Apple PDF pasteboard type",
        "public.png",
        "Apple PNG pasteboard type",
        "public.tiff",
        "NeXT TIFF v4.0 pasteboard type",
        "public.rtf",
        "NeXT Rich Text Format v1.0 pasteboard type",
        "public.utf16-external-plain-text",
        "CorePasteboardFlavorType 0x75743136",
        "com.microsoft.Embed-Source",
        "com.microsoft.Object-Descriptor",
        "com.microsoft.Link-Source",
        "com.microsoft.Link-Source-Descriptor",
        "com.microsoft.Link",
        "com.microsoft.DSP-Text",
        "com.apple.webarchive",
        "Apple Web Archive pasteboard type",
        "com.microsoft.ole.source.46867.0x76580810e0",
        "com.microsoft.DataObject",
        "com.microsoft.appbundleid",
    ];

    const WORD: &[&str] = &[
        "com.microsoft.Object-Descriptor",
        "public.rtf",
        "NeXT Rich Text Format v1.0 pasteboard type",
        "public.utf16-external-plain-text",
        "CorePasteboardFlavorType 0x75743136",
        "public.utf8-plain-text",
        "NSStringPboardType",
        "public.html",
        "Apple HTML pasteboard type",
        "public.utf16-plain-text",
        "CorePasteboardFlavorType 0x75747874",
        "com.adobe.pdf",
        "Apple PDF pasteboard type",
        "com.microsoft.Embed-Source",
        "com.microsoft.Link-Source",
        "com.microsoft.Link-Source-Descriptor",
        "com.microsoft.ObjectLink",
        "com.apple.webarchive",
        "Apple Web Archive pasteboard type",
        "com.apple.flat-rtfd",
        "NeXT RTFD pasteboard type",
        "com.microsoft.ole.source.68486.0x1053dc3c8",
        "com.microsoft.DataObject",
        "com.microsoft.appbundleid",
    ];

    const PAGES: &[&str] = &[
        "com.apple.iWork.TSPNativeData",
        "com.apple.iWork.TSPNativeMetadata",
        "com.apple.iWork.TSPDescription",
        "com.apple.iWork.pasteboardState.applicationName-Pages",
        "com.apple.flat-rtfd",
        "NeXT RTFD pasteboard type",
        "public.rtf",
        "NeXT Rich Text Format v1.0 pasteboard type",
        "public.utf16-external-plain-text",
        "CorePasteboardFlavorType 0x75743136",
        "public.utf8-plain-text",
        "NSStringPboardType",
        "dyn.ah62d4rv4gu8y63n2nuuhg5pbsm4ca6dbsr4gnkduqf31k3pcr7u1e3basv61a3k",
        "NeXT smart paste pasteboard type",
    ];

    #[test]
    fn safari_keeps_the_context_that_2x_threw_away() {
        let kept: Vec<&&str> = SAFARI
            .iter()
            .filter(|id| CATALOG.decide(id) == Take::Payload)
            .collect();
        assert_eq!(CATALOG.classify(SAFARI), Some(Family::Text));
        assert!(kept.len() >= 5, "se guardaron {} tipos", kept.len());
        assert!(kept.iter().any(|id| **id == "com.apple.flat-rtfd"));
        assert!(kept.iter().any(|id| **id == "com.apple.webarchive"));
    }

    #[test]
    fn one_copied_file_does_not_cost_ten_megabytes() {
        assert_eq!(CATALOG.classify(FINDER), Some(Family::Files));
        assert_eq!(CATALOG.decide("com.apple.icns"), Take::Presence);
        for opaque in [
            "CorePasteboardFlavorType 0x6675726C",
            "dyn.ah62d4rv4gu8y6y4grf0gn5xbrzw1gydcr7u1e3cytf2gn",
        ] {
            assert_eq!(CATALOG.decide(opaque), Take::Presence);
        }
        assert_eq!(CATALOG.decide("public.file-url"), Take::Payload);
        let files = CATALOG.classify(FINDER);
        for icon in ["public.tiff", "NeXT TIFF v4.0 pasteboard type"] {
            assert_eq!(CATALOG.decide_in(files, icon), Take::Presence, "{icon}");
        }
        assert_eq!(CATALOG.decide_in(files, "public.file-url"), Take::Payload);
        assert_eq!(
            CATALOG.decide_in(CATALOG.classify(PREVIEW), "public.tiff"),
            Take::Payload
        );
    }

    #[test]
    fn preview_gives_up_the_cheap_representation() {
        assert_eq!(CATALOG.preferred_image(PREVIEW), Some("public.png"));
        assert_eq!(CATALOG.classify(PREVIEW), Some(Family::Image));
        assert_eq!(CATALOG.decide("PVPboardInfoPboardType"), Take::Presence);
    }

    #[test]
    fn the_legacy_twins_of_every_measured_app_collapse() {
        for (legacy, modern) in [
            ("NSStringPboardType", "public.utf8-plain-text"),
            ("NeXT TIFF v4.0 pasteboard type", "public.tiff"),
            ("Apple PNG pasteboard type", "public.png"),
            ("NeXT RTFD pasteboard type", "com.apple.flat-rtfd"),
            ("Apple Web Archive pasteboard type", "com.apple.webarchive"),
        ] {
            assert_eq!(CATALOG.canonical(legacy), modern);
        }
    }

    #[test]
    fn a_spreadsheet_is_text_even_when_it_offers_a_picture_of_itself() {
        assert_eq!(CATALOG.classify(NUMBERS), Some(Family::Text));
        assert_eq!(CATALOG.classify(EXCEL), Some(Family::Text));
        assert_eq!(CATALOG.preferred_image(NUMBERS), Some("public.png"));
    }

    #[test]
    fn a_document_from_word_or_pages_is_text() {
        assert_eq!(CATALOG.classify(WORD), Some(Family::Text));
        assert_eq!(CATALOG.classify(PAGES), Some(Family::Text));
    }

    #[test]
    fn the_document_markers_are_noted_never_read() {
        for marker in CATALOG.embeddable {
            assert_eq!(CATALOG.decide(marker), Take::Presence, "{marker}");
        }
        assert!(
            !CATALOG
                .embeddable
                .iter()
                .any(|marker| CATALOG.images_by_preference.contains(marker))
        );
    }

    #[test]
    fn a_marker_without_text_does_not_hide_an_image() {
        let picture_only = ["com.microsoft.Embed-Source", "public.png"];
        assert_eq!(CATALOG.classify(&picture_only), Some(Family::Image));
    }

    #[test]
    fn the_type_that_hangs_the_app_is_never_asked_for() {
        assert_eq!(
            CATALOG.decide("com.apple.pasteboard.promised-suggested-file-name"),
            Take::Never
        );
    }

    #[test]
    fn every_known_password_marker_is_covered() {
        for marker in [
            "org.nspasteboard.ConcealedType",
            "com.agilebits.onepassword",
            "net.antelle.keeweb",
            "PasswordPboardType",
        ] {
            assert!(
                CATALOG
                    .refusal(&["public.utf8-plain-text", marker])
                    .is_some(),
                "{marker} debe excluir el ítem"
            );
        }
    }
}
