use cp_core::formats::Catalog;

pub const CATALOG: Catalog = Catalog {
    hangs: &["com.apple.pasteboard.promised-suggested-file-name"],
    wasteful: &[
        "com.apple.icns",
        "com.microsoft.Link-Source",
        "com.microsoft.ObjectLink",
    ],
    wanted: &[
        "public.utf8-plain-text",
        "public.rtf",
        "com.apple.flat-rtfd",
        "public.html",
        "com.apple.webarchive",
        "public.png",
        "public.tiff",
        "public.file-url",
        "public.url",
        "public.url-name",
        "org.chromium.source-url",
    ],
    aliases: &[
        ("NSStringPboardType", "public.utf8-plain-text"),
        ("NeXT TIFF v4.0 pasteboard type", "public.tiff"),
        ("Apple PNG pasteboard type", "public.png"),
        ("NeXT Rich Text Format v1.0 pasteboard type", "public.rtf"),
        ("NeXT RTFD pasteboard type", "com.apple.flat-rtfd"),
        ("Apple HTML pasteboard type", "public.html"),
        ("Apple Web Archive pasteboard type", "com.apple.webarchive"),
    ],
    concealed: &[
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "PasswordPboardType",
    ],
    denied_when_zero: &[],
    opaque_prefixes: &["dyn.", "CorePasteboardFlavorType"],
    text: &[
        "public.utf8-plain-text",
        "public.rtf",
        "com.apple.flat-rtfd",
        "public.html",
        "com.apple.webarchive",
    ],
    files: &["public.file-url"],
    images_by_preference: &["public.png", "public.tiff"],
    equivalents: &[],
    embeddable: &[
        "com.apple.iWork.TSPNativeData",
        "com.apple.iWork.TSPNativeMetadata",
        "com.apple.iWork.TSPDescription",
        "com.microsoft.Embed-Source",
        "com.microsoft.Object-Descriptor",
        "com.microsoft.Link-Source-Descriptor",
        "com.microsoft.ObjectLink",
    ],
    page_archives: &["com.apple.webarchive"],
};

#[cfg(test)]
#[path = "formats_test.rs"]
mod tests;
