use cp_core::formats::Catalog;

pub const CATALOG: Catalog = Catalog {
    hangs: &["com.apple.pasteboard.promised-suggested-file-name"],
    wasteful: &[
        "com.apple.icns",
        "com.microsoft.Link-Source",
        "com.microsoft.ObjectLink",
    ],
    wanted: &[
        "public.utf8-plain-text",
        "public.rtf",
        "com.apple.flat-rtfd",
        "public.html",
        "com.apple.webarchive",
        "public.png",
        "public.tiff",
        "public.file-url",
        "public.url",
        "public.url-name",
        "org.chromium.source-url",
    ],
    aliases: &[
        ("NSStringPboardType", "public.utf8-plain-text"),
        ("NeXT TIFF v4.0 pasteboard type", "public.tiff"),
        ("Apple PNG pasteboard type", "public.png"),
        ("NeXT Rich Text Format v1.0 pasteboard type", "public.rtf"),
        ("NeXT RTFD pasteboard type", "com.apple.flat-rtfd"),
        ("Apple HTML pasteboard type", "public.html"),
    ],
    concealed: &[
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "PasswordPboardType",
    ],
    denied_when_zero: &[],
    opaque_prefixes: &["dyn.", "CorePasteboardFlavorType"],
    text: &[
        "public.utf8-plain-text",
        "public.rtf",
        "com.apple.flat-rtfd",
        "public.html",
        "com.apple.webarchive",
    ],
    files: &["public.file-url"],
    images_by_preference: &["public.png", "public.tiff"],
    equivalents: &[],
    embeddable: &[],
};

#[cfg(test)]
mod tests {
    use super::CATALOG;
    use cp_core::formats::{Family, Take};

    const SAFARI: &[&str] = &[
        "com.apple.webarchive",
        "Apple Web Archive pasteboard type",
        "com.apple.flat-rtfd",
        "NeXT RTFD pasteboard type",
        "public.rtf",
        "NeXT Rich Text Format v1.0 pasteboard type",
        "public.html",
        "Apple HTML pasteboard type",
        "public.utf8-plain-text",
        "NSStringPboardType",
        "com.apple.WebKit.custom-pasteboard-data",
    ];

    const FINDER: &[&str] = &[
        "public.file-url",
        "CorePasteboardFlavorType 0x6675726C",
        "dyn.ah62d4rv4gu8y6y4grf0gn5xbrzw1gydcr7u1e3cytf2gn",
        "NSFilenamesPboardType",
        "com.apple.finder.noderef",
        "fndf",
        "public.utf8-plain-text",
        "com.apple.icns",
        "public.tiff",
        "NeXT TIFF v4.0 pasteboard type",
    ];

    const PREVIEW: &[&str] = &[
        "public.png",
        "Apple PNG pasteboard type",
        "dyn.ah62d4rv4gu8zazwuqm10c6xemf1gq54uqm10c6xenv61a3k",
        "PVPboardInfoPboardType",
        "public.tiff",
        "NeXT TIFF v4.0 pasteboard type",
    ];

    #[test]
    fn safari_keeps_the_context_that_2x_threw_away() {
        let kept: Vec<&&str> = SAFARI
            .iter()
            .filter(|id| CATALOG.decide(id) == Take::Payload)
            .collect();
        assert_eq!(CATALOG.classify(SAFARI), Some(Family::Text));
        assert!(kept.len() >= 5, "se guardaron {} tipos", kept.len());
        assert!(kept.iter().any(|id| **id == "com.apple.flat-rtfd"));
        assert!(kept.iter().any(|id| **id == "com.apple.webarchive"));
    }

    #[test]
    fn one_copied_file_does_not_cost_ten_megabytes() {
        assert_eq!(CATALOG.classify(FINDER), Some(Family::Files));
        assert_eq!(CATALOG.decide("com.apple.icns"), Take::Presence);
        for opaque in [
            "CorePasteboardFlavorType 0x6675726C",
            "dyn.ah62d4rv4gu8y6y4grf0gn5xbrzw1gydcr7u1e3cytf2gn",
        ] {
            assert_eq!(CATALOG.decide(opaque), Take::Presence);
        }
        assert_eq!(CATALOG.decide("public.file-url"), Take::Payload);
    }

    #[test]
    fn preview_gives_up_the_cheap_representation() {
        assert_eq!(CATALOG.preferred_image(PREVIEW), Some("public.png"));
        assert_eq!(CATALOG.classify(PREVIEW), Some(Family::Image));
        assert_eq!(CATALOG.decide("PVPboardInfoPboardType"), Take::Presence);
    }

    #[test]
    fn the_legacy_twins_of_every_measured_app_collapse() {
        for (legacy, modern) in [
            ("NSStringPboardType", "public.utf8-plain-text"),
            ("NeXT TIFF v4.0 pasteboard type", "public.tiff"),
            ("Apple PNG pasteboard type", "public.png"),
            ("NeXT RTFD pasteboard type", "com.apple.flat-rtfd"),
        ] {
            assert_eq!(CATALOG.canonical(legacy), modern);
        }
    }

    #[test]
    fn the_type_that_hangs_the_app_is_never_asked_for() {
        assert_eq!(
            CATALOG.decide("com.apple.pasteboard.promised-suggested-file-name"),
            Take::Never
        );
    }

    #[test]
    fn every_known_password_marker_is_covered() {
        for marker in [
            "org.nspasteboard.ConcealedType",
            "com.agilebits.onepassword",
            "net.antelle.keeweb",
            "PasswordPboardType",
        ] {
            assert!(
                CATALOG
                    .refusal(&["public.utf8-plain-text", marker])
                    .is_some(),
                "{marker} debe excluir el ítem"
            );
        }
    }
}
