display_name: CopyPaste
icon: assets/icons/icon_app_256.png
summary: A clipboard history manager
group: Utilities
vendor: rgdevment
packager: rgdevment
packagerEmail: rgdevment@apirest.cl
license: GPLv3
url: https://github.com/rgdevment/CopyPaste
generic_name: Clipboard Manager
startup_notify: true
categories:
  - Utility
keywords:
  - clipboard
  - copy
  - paste
