/// Qué hacer con un tipo que la fuente ofreció.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Take {
    /// Se copian los bytes.
    Payload,
    /// Se anota que existía, con su tamaño, sin pedir los datos.
    Presence,
    /// No se toca nunca.
    Never,
}

/// Pedir los datos de este tipo cuelga la aplicación indefinidamente.
const HANGS: &[&str] = &["com.apple.pasteboard.promised-suggested-file-name"];

/// Arrastran megabytes sin aportar nada recuperable.
const WASTEFUL: &[&str] = &[
    "com.microsoft.Link-Source",
    "com.microsoft.ObjectLink",
    "com.apple.icns",
];

const WANTED: &[&str] = &[
    "public.utf8-plain-text",
    "public.rtf",
    "com.apple.flat-rtfd",
    "public.html",
    "com.apple.webarchive",
    "public.png",
    "public.tiff",
    "public.file-url",
    "public.url",
    "public.url-name",
    "org.chromium.source-url",
];

const ALIASES: &[(&str, &str)] = &[
    ("NSStringPboardType", "public.utf8-plain-text"),
    ("NeXT TIFF v4.0 pasteboard type", "public.tiff"),
    ("Apple PNG pasteboard type", "public.png"),
    ("NeXT Rich Text Format v1.0 pasteboard type", "public.rtf"),
    ("NeXT RTFD pasteboard type", "com.apple.flat-rtfd"),
    ("Apple HTML pasteboard type", "public.html"),
];

/// La presencia de cualquiera de estos significa «no registres esto». Se mira
/// el tipo, nunca el contenido: KeePassXC y KeePassium ponen el secreto en
/// claro dentro del payload, así que leerlo para decidir ya sería demasiado.
const CONCEALED: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
    "com.typeit4me.clipping",
    "Pasteboard generator type",
    "net.antelle.keeweb",
    "PasswordPboardType",
];

pub fn canonical(uti: &str) -> &str {
    ALIASES
        .iter()
        .find(|(legacy, _)| *legacy == uti)
        .map_or(uti, |(_, modern)| *modern)
}

pub fn decide(uti: &str) -> Take {
    let uti = canonical(uti);
    if HANGS.contains(&uti) {
        return Take::Never;
    }
    if WASTEFUL.contains(&uti)
        || uti.starts_with("dyn.")
        || uti.starts_with("CorePasteboardFlavorType")
    {
        return Take::Presence;
    }
    if WANTED.contains(&uti) {
        return Take::Payload;
    }
    Take::Presence
}

pub fn is_concealed(offered: &[&str]) -> bool {
    offered.iter().any(|uti| CONCEALED.contains(uti))
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    Text,
    Image,
    Files,
}

/// El tipo mostrado es una clasificación sobre el conjunto, nunca una elección
/// que descarte lo demás.
pub fn classify(offered: &[&str]) -> Option<Kind> {
    let known: Vec<&str> = offered.iter().map(|uti| canonical(uti)).collect();
    if known.contains(&"public.file-url") {
        return Some(Kind::Files);
    }
    if known.contains(&"public.png") || known.contains(&"public.tiff") {
        return Some(Kind::Image);
    }
    if known.iter().any(|uti| {
        matches!(
            *uti,
            "public.utf8-plain-text" | "public.rtf" | "com.apple.flat-rtfd" | "public.html"
        )
    }) {
        return Some(Kind::Text);
    }
    None
}

/// Entre dos representaciones del mismo pixel, la más barata. Medido el
/// 12/09/2026: la misma imagen desde Preview pesa 381 B en PNG y 19.844 en
/// TIFF, y el TIFF además pierde la representación Retina.
pub fn preferred_image(offered: &[&str]) -> Option<&'static str> {
    let known: Vec<&str> = offered.iter().map(|uti| canonical(uti)).collect();
    if known.contains(&"public.png") {
        return Some("public.png");
    }
    if known.contains(&"public.tiff") {
        return Some("public.tiff");
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_type_that_hangs_is_never_asked_for() {
        assert_eq!(
            decide("com.apple.pasteboard.promised-suggested-file-name"),
            Take::Never
        );
    }

    #[test]
    fn copying_one_file_does_not_drag_ten_megabytes_of_icon() {
        let finder = [
            "public.file-url",
            "NSFilenamesPboardType",
            "com.apple.icns",
            "public.tiff",
            "public.utf8-plain-text",
            "com.apple.finder.noderef",
        ];
        for uti in ["com.apple.icns", "public.tiff", "NSFilenamesPboardType"] {
            let taken = decide(uti);
            if uti == "public.tiff" {
                assert_eq!(taken, Take::Payload, "el TIFF es la imagen, no el icono");
            } else {
                assert_ne!(taken, Take::Payload, "{uti} no se copia entero");
            }
        }
        assert_eq!(decide("public.file-url"), Take::Payload);
        assert_eq!(classify(&finder), Some(Kind::Files));
    }

    #[test]
    fn png_wins_over_tiff_when_both_are_offered() {
        assert_eq!(
            preferred_image(&["public.tiff", "public.png"]),
            Some("public.png")
        );
        assert_eq!(preferred_image(&["public.tiff"]), Some("public.tiff"));
    }

    #[test]
    fn legacy_twins_collapse_onto_the_modern_type() {
        assert_eq!(canonical("NeXT TIFF v4.0 pasteboard type"), "public.tiff");
        assert_eq!(canonical("Apple PNG pasteboard type"), "public.png");
        assert_eq!(canonical("NSStringPboardType"), "public.utf8-plain-text");
        assert_eq!(canonical("public.png"), "public.png");
    }

    #[test]
    fn a_password_is_recognised_by_the_type_alone() {
        assert!(is_concealed(&[
            "public.utf8-plain-text",
            "org.nspasteboard.ConcealedType"
        ]));
        assert!(!is_concealed(&["public.utf8-plain-text"]));
    }

    #[test]
    fn safari_keeps_everything_it_offered() {
        let safari = [
            "com.apple.webarchive",
            "com.apple.flat-rtfd",
            "public.rtf",
            "public.html",
            "public.utf8-plain-text",
            "com.apple.WebKit.custom-pasteboard-data",
        ];
        let kept: Vec<&str> = safari
            .iter()
            .filter(|uti| decide(uti) == Take::Payload)
            .copied()
            .collect();
        assert_eq!(
            kept.len(),
            5,
            "solo el tipo privado de WebKit se deja fuera"
        );
        assert_eq!(classify(&safari), Some(Kind::Text));
    }

    #[test]
    fn an_image_copied_with_its_url_is_still_an_image() {
        let safari = ["public.url", "public.utf8-plain-text", "public.png"];
        assert_eq!(classify(&safari), Some(Kind::Image));
        assert_eq!(decide("public.url"), Take::Payload);
    }
}
